set(primary "${TEST_ROOT}/steamapps/common/清单游戏")
set(api_directory "${TEST_ROOT}/API 游戏")
file(MAKE_DIRECTORY "${primary}" "${api_directory}")
file(WRITE "${TEST_ROOT}/steamapps/appmanifest_70.acf"
    "\"AppState\" { \"installdir\" \"清单游戏\" }")
file(TO_NATIVE_PATH "${primary}" primary_native)
file(TO_NATIVE_PATH "${api_directory}" api_native)
set(ENV{STEAM_TEST_EXPECTED_APPID} "70")
set(ENV{STEAM_TEST_INSTALL_DIR} "${api_native}")
set(ENV{STEAM_TEST_SHUTDOWN_FILE} "")

function(check_command expected_code expected_output)
    execute_process(COMMAND ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE diagnostics
        ENCODING UTF-8 TIMEOUT 15)
    if(NOT "${result}" STREQUAL "${expected_code}")
        message(FATAL_ERROR "Expected exit ${expected_code}, got ${result}: ${diagnostics}")
    endif()
    if(NOT "${output}" STREQUAL "${expected_output}")
        message(FATAL_ERROR "Unexpected stdout: [${output}], expected [${expected_output}]")
    endif()
    set(command_diagnostics "${diagnostics}" PARENT_SCOPE)
endfunction()

set(ENV{STEAM_TEST_MODE} "success")
check_command(0 "${api_native}\n" "${HARNESS}" 70 "${TEST_ROOT}" "${DLL}")
if(NOT command_diagnostics MATCHES "SDK diagnostic on stdout" OR
    NOT command_diagnostics MATCHES "SDK shutdown diagnostic on stdout")
    message(FATAL_ERROR "SDK diagnostics must reach stderr, including shutdown")
endif()
foreach(mode init-fails null-interface query-fails)
    set(ENV{STEAM_TEST_MODE} "${mode}")
    check_command(0 "${primary_native}\n" "${HARNESS}" 70 "${TEST_ROOT}" "${DLL}")
endforeach()
check_command(0 "${primary_native}\n" "${HARNESS}" 70 "${TEST_ROOT}" "${TEST_ROOT}/missing.dll")
check_command(0 "${primary_native}\n" "${HARNESS}" 70 "${TEST_ROOT}" "${INCOMPLETE_DLL}")
check_command(6 "" "${HARNESS}" 10 "${TEST_ROOT}" "${DLL}")
check_command(1 "" "${PROGRAM}")
check_command(1 "" "${PROGRAM}" 0)
check_command(1 "" "${PROGRAM}" 70x)
check_command(1 "" "${PROGRAM}" 4294967296)
check_command(1 "" "${PROGRAM}" 70 10)
message(STATUS "12 command scenarios passed")
